### ISSUE TITLE
"Current Stake" appears in Node details page in case "Stake for Consensus" is 0

### ISSUE THREAD

**Issue by Neurone** [hashgraph/hedera-mirror-node-explorer#1231]
### Description

Exploring the Node details pages I noticed that when the "Stake for Consensus" is 0, a new value "Current Stake" appears in the page.

Also, I cannot find that value looking at the normal Mirror Node queries for [general stake](https://mainnet-public.mirrornode.hedera.com/api/v1/network/stake) and [node details](https://mainnet-public.mirrornode.hedera.com/api/v1/network/nodes), so I'm not sure if it's correct, and if it's correct to show it only when the stake for consensus is 0.

### Steps to reproduce

1. Check https://hashscan.io/mainnet/node/2 and notice "Stake for Consensus" field, and after that the "Min Stake" field.
2. Check https://hashscan.io/mainnet/node/3 and notice "Stake for Consensus" field is 0, and a new "Current Stake" field with value 389,313,830 HBAR appeared.
3. Check any other non-0 staking node (i.e. https://hashscan.io/mainnet/node/4) and the "Current Stake" field disappear again.

### Additional context

<img width="899" alt="01-normal" src="https://github.com/user-attachments/assets/721422a0-534d-45c4-ae83-4abb8020202f">
<img width="905" alt="02-strange" src="https://github.com/user-attachments/assets/956c18ba-6e91-4784-8cbc-c59e2f72e06b">

### Hedera network

mainnet

### Version

v24.4.0-172-g40d35e7

### Operating system

None

**Comment by svienot** [comment]
Hi @Neurone  -- thanks for reporting this issue.

According to the current explorer logic, things should actually be displayed like below (note this change has been deployed on staging):

<img width="1149" alt="Screenshot 2024-08-01 at 19 18 49" src="https://github.com/user-attachments/assets/dc5217cd-0531-4e0b-8d54-8ba67a263274">

So the logic is that we process `unclamped_stake = stake_rewarded + stake_not_rewarded`

1. When `unclamped_stake >= min_stake`, the node takes part in consensus and we just display its `stake` (“Stake for Consensus”).
2. When `unclamped_stake < min_stake`, the node does not take part in consensus, so its `stake` (“Stake for Consensus”) is `0`.  In that case we also display the `unclamped_stake` (“Current Stake”) to explain the `0` and show where the node stands compared to the minimum which would allow it to participate.

Would it be less confusing if the “Current Stake” was always displayed ?

[What I am not sure about, is how the stake value is determined by the network in case (1) since its seems we have `stake > stake_rewarded + stake_not_rewarded`…]
