### ISSUE TITLE
Display the build version, not just the build date/time

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#137]
### Problem

When submitting tickets, it requests that I have the build version number but https://hashscan.io/ only displays the build date/time.

### Solution

Can we display the build version, next to the build date/time?

### Alternatives

None

**Comment by svienot** [comment]
We currently have a continuous deployment setup for the explorer, and do not have versions.
I suppose we could generate a build number, but that would not be of any use unless we also generate some correspondance between that build number and the build content.

Since it is possible to provide the build date in the github submission form, it seems a bit hard to justify the effort of managing a build number.

**Comment by Neurone** [comment]
Hi @svienot, here #171 you can find a PR that uses the commit hash as release number. This complies with the idea of non-managing an explicit version number, but allows to compare different builds, regardless of the time of the building.
