### ISSUE TITLE
Add Arweave support for NFT Metadata

### ISSUE THREAD

**Issue by mb-swirlds** [hashgraph/hedera-mirror-node-explorer#1396]
### Problem

Can we get Arweave stored metadata files indexed and displaying properly on HashScan.

Right now metadata stored in areweave will not show.

Example:
https://hashscan.io/mainnet/token/0.0.1518294/2?p=1&p1=1&k1=1672434637.410991003

Metadata URL: https://arweave.net/accqwldSOZL84IGcrnPTIt6FgNQTOlsSyEXS4-u8kk4

See UI:
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/9b132e12-2f19-422e-b66c-5758f83bb018">

### Solution

Can we index or retrieve arweave urls and display accordingly?

### Alternatives

There really is only one possible option to accept arweave as a storage solution for Token Metadata.

**Comment by svienot** [comment]
I see in the metadata that the `ar://` URI scheme is used to locate the image.

I am wondering why such URI scheme is not used to locate the metadata JSON file as well (i.e. the decoded metadata field of the token would be `ar://accqwldSOZL84IGcrnPTIt6FgNQTOlsSyEXS4`). This would greatly help determine for sure this is stored on Arweave. Explorer might otherwise query the Arweave server with a hash which is not an Arweave hash.

**Comment by KingDaVinciGraph** [comment]
> I see in the metadata that the `ar://` URI scheme is used to locate the image.
> 
> I am wondering why such URI scheme is not used to locate the metadata JSON file as well (i.e. the decoded metadata field of the token would be `ar://accqwldSOZL84IGcrnPTIt6FgNQTOlsSyEXS4`). This would greatly help determine for sure this is stored on Arweave. Explorer might otherwise query the Arweave server with a hash which is not an Arweave hash.

Hi there 
This article can solve the problem 
https://davincigraph.medium.com/how-dapps-can-utilize-arweave-data-storage-for-nfts-on-hedera-hashgraph-404086170c6c

**Comment by KingDaVinciGraph** [comment]
https://docs.opensea.io/docs/metadata-standards#ipfs-and-arweave-uris

IPFS and Arweave URIs
OpenSea supports the storage of NFT metadata in decentralized file networks, so that they can’t be modified by a central party.

If you use [IPFS](https://ipfs.io/) to host your metadata, your URL should be in the format ipfs://<hash>. For example, ipfs://QmTy8w65yBXgyfG2ZBg5TrfB2hPjrDQH3RCQFJGkARStJb. If you plan to store on IPFS, we recommend [Pinata](https://pinata.cloud/) for easily storing data. Here's a tutorial by Chainlink for getting started: https://blog.chain.link/build-deploy-and-sell-your-own-dynamic-nft/.

[Arweave](https://www.arweave.org/)'s equivalent is ar://<hash>. For example, ar://jK9sR4OrYvODj7PD3czIAyNJalub0-vdV_JAg1NqQ-o.


https://davincigraph.medium.com/how-dapps-can-utilize-arweave-data-storage-for-nfts-on-hedera-hashgraph-404086170c6c
