### ISSUE TITLE
Missing fungible token balances

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#1413]
### Description

![image](https://github.com/user-attachments/assets/b661e82d-6edb-4ae1-b2f0-20aa14026539)

### Steps to reproduce

see above

### Version

na

### Operating system

None

**Comment by svienot** [comment]
Here is an example of mainnet account which exhibits this issue: 0.0.768084

**Comment by svienot** [comment]
This issue is exhibited by accounts which have large amounts of token.
After investigation, it turns out this is due to the fact we still use the REST endpoint `api/v1/balances?account.id={id}` to retrieve the balances of an account (the call returns a max of 50 token balances per account so its use is discouraged for the present use case). We should instead use either  `/api/v1/accounts/{id}/tokens` or `/api/v1/tokens/{id}/balance`

**Comment by timi-codes** [comment]
Hello @svienot , I'm happy to jump on this fix.

**Comment by timi-codes** [comment]
Hi @svienot,  on checking this, I can see `/api/v1/accounts/{id}/tokens` is now being used.

<img width="1909" alt="image" src="https://github.com/user-attachments/assets/a5cf292c-b3c6-4cc0-a031-36e45e53e985">
