### ISSUE TITLE
Rename any usage of “Hedera”, “Swirlds” or “Hashgraph” to “Hiero”

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#1430]
### Problem

This project will be listed under the Linux Foundation Hiero project. This projects needs to rename any rename any usage of “Hedera”, “Swirlds” or “Hashgraph” to “Hiero.” 

### Solution

This projects needs to rename any rename any usage of “Hedera”, “Swirlds” or “Hashgraph” to “Hiero.”

**Comment by svienot** [comment]
Closing this issue since (hopefully) all remaining occurrences of (_Hedera_, _Hashgraph_, _Swirlds_) should now have been renamed to _Hiero_.

The following exceptions remain:

- copyright notices in all source files
- paths for files, repositories, etc...

The assumption is the above exceptions can be addressed at a later stage (but while they remain, it is harder to make sure there is no other occurence left).
