### ISSUE TITLE
Optimize Explorer for SEO

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-mirror-node-explorer#200]
### Problem

Request from Brady Gentile: `I think we should optimize hashscan for SEO`

### Solution

To be investigated.

**Comment by svienot** [comment]
Closing this since a first round of modifications on the HTML meta tags have fixed the most prominent issue reported.
A google search request for 'hashscan' now returns hashscan.io in 1st position with the following summary:
_HashScan is a ledger explorer for the Hedera network and allows you to explore and search the network for transactions, accounts, tokens and contracts._
Let's create specific enhancements for potential further SEO optimizations.
