### ISSUE TITLE
Support EVM address to display Contracts in addition to Contract Id

### ISSUE THREAD

**Issue by CoveMB** [hashgraph/hedera-mirror-node-explorer#338]
### Problem

When navigating to https://hashscan.io/testnet/account/_CONTRACT_EVM_ADDRESS_ the page display information as if it is an account instead of a contract.

example: https://hashscan.io/testnet/account/0x0000000000000000000000000000000002eAE879

### Solution

It would be useful if the explorer could detect if the address is a contract and display contract-related data like bytecode and such.

**Comment by svienot** [comment]
In fact, it does detect it, and provides a link allowing to navigate to the ContractDetails view.
<img width="881" alt="Screenshot 2022-11-24 at 20 29 25" src="https://user-images.githubusercontent.com/16097111/203854620-6ab184fb-aaf3-481b-a336-103e7dc95753.png">

**Comment by BjMrq** [comment]
Which redirects to this https://hashscan.io/testnet/contract/0x0000000000000000000000000000000002eAE879
With a `Invalid contract ID: 0x0000000000000000000000000000000002eAE879` error. Not sure it is a very good UX.

Navigating to `/address` already redirect automatically to `/account` https://hashscan.io/testnet/address/0x0000000000000000000000000000000002eAE879

Maybe it would be interesting not to have to navigate, stay under `/address` and display contract info like on other explorer like Etherscan

**Comment by svienot** [comment]
The navigation to the ContractDetails view is broken, we are going to fix this ASAP.
Beyond that, we could indeed consider merging the AccountDetails and ContractDetails views.
Thanks for reporting this and for your feedback.

**Comment by svienot** [comment]
- We now support `<explorer-url>/testnet/contract/<evm-address>` as well as  `<explorer-url>/testnet/contract/<id>`
- `<explorer-url>/testnet/account/` and  `<explorer-url>/testnet/contract/` are native explorer routes which will continue to show respectively an _account view_ and a _contract view_, since account and contract are distinct entities in the native Hedera context
- For user flows originating from the Ethereum world, the exposed route is:  `<explorer-url>/testnet/address/<evm-address>` which will automatically route to a _contract view_ or an _account view_ as appropriate, and to an _Inactive EVM Address_ page when the address has not yet been created.
