### ISSUE TITLE
Accounts With Empty Info

### ISSUE THREAD

**Issue by EliAzev** [hashgraph/hedera-mirror-node-explorer#42]
### Description

Accounts ID from 101 to 799 do not show public key neither Auto renew Period on explorers.

### Steps to reproduce

1. Search the referred account ID in any hedera explorer.

### Hedera network

mainnet

### Version

v0.25.x

### Operating system

Windows

**Comment by ericleponner** [comment]
Explorer shows empty strings because the mirror node REST API provides null values for these properties. 

We suggest your opening a bug against the mirror-node project if you believe this should not be the case. 
On the explorer side, we might display 'None' instead of an empty string to avoid any ambiguity.

**Comment by EliAzev** [comment]
> Explorer shows empty strings because the mirror node REST API provides null values for these properties.
> 
> We suggest your opening a bug against the mirror-node project if you believe this should not be the case. On the explorer side, we might display 'None' instead of an empty string to avoid any ambiguity.
Oh ok, thank you for the informative answer.
