### ISSUE TITLE
mirror node does not allow searching for block by 32 byte hash

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#426]
### Description

Etherscan allows for blocks to be searched using their 32 byte blockHash for example [eth mainnet block 16490362](https://etherscan.io/block/0x149092d5a6d5d456251e1d381cbbba68a46c0c1664ffcb1a8885a5cecaa47b6d).

However on hashscan the 48 byte blockHash has to be used for example [hedera previewnet block 244702](https://hashscan.io/previewnet/block/0xc5549204a0fe23df12e374a7bff02725c818a4d96a05f2eceb94036e16d6544ac7c03dc38f2acb0273aad6669d7fcc30).

Hashscan should support the 32 byte blockHash as well.

### Steps to reproduce

The above description is sufficient evidence of the issue.

### Hedera network

previewnet

### Version

mirror-node@0.72.0

### Operating system

None

**Comment by svienot** [comment]
Since mirror node supports look-up using both 48-byte hash its 32-byte prefix:

- https://previewnet.mirrornode.hedera.com/api/v1/blocks/c5549204a0fe23df12e374a7bff02725c818a4d96a05f2eceb94036e16d6544a 
- https://previewnet.mirrornode.hedera.com/api/v1/blocks/c5549204a0fe23df12e374a7bff02725c818a4d96a05f2eceb94036e16d6544ac7c03dc38f2acb0273aad6669d7fcc30 

we should probably also support both forms in HashScan.
