### ISSUE TITLE
contract path should accept both contract id and evm address

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#432]
### Problem

`/account/{evm_address}` and `/account/{contractId}` both work, however `/contract/{contractId}` works and `/contract/{evm_address}` does not work.

Works - https://hashscan.io/testnet/account/0.0.8478
Works - https://hashscan.io/testnet/account/0x8cf15cbaa069bb1ba1e932f08eed5d8c00b4a2ad

Works - https://hashscan.io/testnet/contract/0.0.8478
Does NOT work - https://hashscan.io/testnet/contract/0x8cf15cbaa069bb1ba1e932f08eed5d8c00b4a2ad

### Solution

See above.

**Comment by ed-marquez** [comment]
HashScan supports searching by
:white_check_mark: account id (https://hashscan.io/testnet/account/0.0.3888934) and by account address (https://hashscan.io/testnet/account/0x00000000000000000000000000000000003b5726).
:white_check_mark: token id (https://hashscan.io/testnet/token/0.0.3889505) and by token address (https://hashscan.io/testnet/token/0x00000000000000000000000000000000003b5961)
The same is not true for contracts
:white_check_mark: by contract ID works: https://hashscan.io/testnet/contract/0.0.3889140 (REST API https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.3889151)
**:x: by contract address does not : https://hashscan.io/testnet/contract/0x00000000000000000000000000000000003b57f4?p=1** (REST API https://testnet.mirrornode.hedera.com/api/v1/contracts/0x00000000000000000000000000000000003b5961)


+1 to this issue being very important. 
Currently, when working with EVM tools, it's difficult to obtain contract information from mirror nodes. That's because these tools return the contract's EVM address (not contract ID). The Hethers JS utility to convert from Address to ID is currently not working as expected, so there's no way to go from address to id for contracts.

Does the REST API expect the Solidity Address instead of EVM address?
https://docs.hedera.com/hedera/sdks-and-apis/rest-api#api-v1-contracts-contractidoraddress

**Comment by ericleponner** [comment]
HashScan implements [IEP 3091](https://eips.ethereum.org/EIPS/eip-3091).
URL for searching account / contract is: `https://{network}/address/{accountAddress}`.
This is url is documented and committed.
Does it satisfy your needs ?

**Comment by mshakeg** [comment]
@ericleponner yes it does, `https://{network}/address/{evmAddress}` redirects to `https://{network}/contract/{contractId}`.

Though is there a reason `https://{network}/contract/{evmAddress}` is not supported as well? It seems simple enough.

**Comment by ed-marquez** [comment]
@ericleponner 
not sure what is meant by `It's not complex but it transforms a simple URL as an API.` The mirror node REST API already implements that endpoint. 
`https://testnet.mirrornode.hedera.com/api/v1/contracts/0x00000000000000000000000000000000003b57f4`, so in a way it's already documented. Let me know if I'm confusing terms here.

My concern is consistency. Not having that URL available introduces a friction point for developers and end users trying to get info on contracts. It would be best for usability to provide it. As we create tutorials, demos, and applications, that consistency will go a long way. 

I'm ok with keeping the `address` redirects anonymous. We don't need to introduce those publicly because they only support `contract addresses` and `account addresses` - not token addresses.
