### ISSUE TITLE
Show NFT Collections

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#525]
### Problem

As a user I would like to view an account's associated HTS NFT collections.
As a user I would like to click on a specific account's NFT collection and view all NFTs owned by serial_id.

### Solution

1. get an account's tokens from the mirror node using `/api/v1/accounts/{accountId}/tokens`
2. filter the above tokens for only NFTs
3. get all serial_ids owned using `/api/v1/tokens/{nftId}/nfts` for each NFT

**Comment by svienot** [comment]
I am not sure how what you describes differs from what is already in place.

On the account view, we list all balances (hbar, fungible tokens and NFTs).
For instance in the balances of this account:
<img width="695" alt="Balances" src="https://user-images.githubusercontent.com/16097111/229453170-e3b5524d-014d-41cd-8bdc-126a765d10e6.png">
HSNFT is a class of NFT and the balance indicates the account holds 7 instances of that.
When you click on HSNFT and navigate to the token view, there is the list of all NFT owned by serial numbers.

Are you suggesting we list separately fungible and NFT on the account view?
(note that most of the time there is a link to view all token balances on a separate page since there are too many).

What we had in mind was to enumerate the serial numbers after the NFT label on the account view.
For instance here we might display:
    `7 HSNFT (#1, #3, #4, #5, #6, #7, #8)`
and above a given number of serial-ids we might provide a link to view the serial numbers owned on a separate page:
    `7 HSNFT (view serial numbers)`

**Comment by mshakeg** [comment]
@svienot correct, part of what I'm suggesting is that the fungible tokens and NFTs be separately listed on the account view.

However, the core issue is that clicking on the NFT on the Account view's balances section redirects to the token view page i.e. `/token/{tokenId}` which lists all NFT Holders and the `serial_id` that each account owns. However, IMO it would make more sense to navigate to a page which lists all serial_ids owned by that specific account.

**Comment by Sheng-Long** [comment]
related to https://github.com/hashgraph/hedera-mirror-node-explorer/issues/12
