### ISSUE TITLE
Add release versioning to the explorer

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#585]
### Problem

As a user, I would like to know the version of the mirror node explorer.

Users can currently see the build timestamp on the bottom left of the explorer, however versioning with Github release notes of all changes between versions would be ideal, especially when viewing a non-Hashscan explorer(where the build time isn't easily accessible) such as https://explorer.arkhia.io/

### Solution

See above.

**Comment by mshakeg** [comment]
@ericleponner all user-visible changes or all issues that were completed in that release(that details all user-visible changes).

**Comment by svienot** [comment]
We do not manage _releases_ for HashScan. We do continuous deployment, so every time a PR is merged (whether bug fix or feature), HashScan is redeployed. 

We could build (automatically) a release note to keep track of what was added, and when, but it would be similar to the commit history of the main branch of the repository.

**Comment by mshakeg** [comment]
@svienot I see, that could work, and perhaps also bump the `version`(in the `package.json`) as part of the workflow and commit that, and also show it on Hashscan.

**Comment by Neurone** [comment]
I suggest resurrecting this proposal #171 :)

**Comment by SimiHunjan** [comment]
Would it be helpful to maintain milestones for issues that were completed and deployed over a month timespan and then generate corresponding release notes based on what was deployed for the month? Here is an example milestone https://github.com/hashgraph/hedera-mirror-node-explorer/milestone/5. Then the corresponding release notes would live here https://github.com/hashgraph/hedera-mirror-node-explorer/releases for that milestone.

**Comment by svienot** [comment]
On top of our continuous deployment process (every PR integrated into main is pushed in production) we are going to put in place the following scheme to identify (tag) _releases_, which will be made available as docker images in the Hedera container registry:
- we will tag a release every month. The version number will reflect the year and month, for instance `v23.5.0` is the monthly release tagged in May of 2023.
- we may tag releases between monthly releases when there is a fix or enhancement worth making a new Docker image available. E.g. the first bug fix release after May release would be `v23.5.1`
- the explorer UI displays an extended version number, in the same format provided by `git describe`, in addition to the build date. This format includes the version (as tagged), number of commits since the tag, and the current commit hash.
E.g.  `Release v23.5.0-1-g2e67e92 built Thu, 18 May 2023 15:27:19 GMT` 
- the version string is a link to `https://github.com/hashgraph/hedera-mirror-node-explorer/releases`

@Neurone I think your proposal https://github.com/hashgraph/hedera-mirror-node-explorer/pull/171 will address this last point perfectly, given a couple tiny modifications I will detail in the PR.

**Comment by svienot** [comment]
Hashscan now displays the release + commit hash + build date.
As of next release, the [release notes page](https://github.com/hashgraph/hedera-mirror-node-explorer/releases) will recap changes.
