### ISSUE TITLE
Search for TopicId returns no result

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node-explorer#713]
### Description

On testnet, searching for topic id 0.0.3671631 returns `No result` yet the topic id does indeed exist
https://hashscan.io/testnet/topic/0.0.3671631

### Steps to reproduce

Search for topic id 0.0.3671631, witness no result
Look for the same topic id in the https://hashscan.io/testnet/topics and it is there.

### Hedera network

testnet

### Version

v23.8.0-14-g9e316a2

### Operating system

None

**Comment by ericleponner** [comment]
This behavior is the result of a compromise.

Mirror node does not expose any `topic` entity: it exposes only `topic message` entity which is reflected by mirror node API:
```
/api/v1/topics/{topicId}/messages
/api/v1/topics/{topicId}/messages/{sequenceNumber}

// There is no /api/v1/topics/{topicId} call
```

HashScan has no mean to known if a `topic` exists or not: it can only know if `topic message`'s match a certain id.

In `Search Bar`, when searched topic id has no associated message, we had two options :
1) return a `topic not found` result
2) return an `empty message table` result

We choose 1). But we can move to 2) if required.

https://hashscan.io/testnet/topic/0.0.3671631 returns an `empty message table` because HashScan assumes this URL comes from Recent Topics table page and in this context topics does exist but has no message.

**Comment by ericleponner** [comment]
> In Search Bar, when searched topic id has no associated message, we had two options :
> 
> 1) return a topic not found result
> 2) return an empty message table result
> 
> We choose 1). But we can move to 2) if required.
> 

In fact, no : option 2) is not possible. If we were doing that, HashScan would return an empty topic message table for any non existing entity id (account, contract, topic, token …).

Not sure we can have a better behavior without adding `/api/v1/topics/{topicId}` in mirror node.

**Comment by gregscullard** [comment]
Understood, it may be worth adding a topic entity to the mirror, not being able to see topic information (such as we can see for contracts, tokens, accounts...) is odd.

**Comment by svienot** [comment]
This issues depends on: [#774](https://github.com/hashgraph/hedera-mirror-node/issues/774)
