### ISSUE TITLE
Smart contract verification phase 2 feedback 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#739]
### Problem

- Move the verify contract button to the top right in the contract source box
- For labels for smart contract verification use: Full Match, Partial Match, Not Verified 
- Add link to the Sourcify files for the verified contract
- Provide messaging in that the meta data file is not required, but can increase your changes of a full match

### Solution

Add the above

**Comment by Reccetech** [comment]
So I think we are having a lot of churn about how to display the source code. A few options discussed:
- We only display the source code of the "main" file.
- We display one box will all of the source code combined
- We display the source code of individual source code files (like etherscan)
- We break the source code display into a new page
- We provide a link to the source code in the Sourcify repo.

So here is my suggestion.
- We display the byte code for verified contracts
- In Phase 2 we take a KISS approach and for the source code we just provide a link to the Sourcify repo and do not attempt to display the source code within Hashscan. This will allow us to stay on schedule for a phase 2 release. I realize its not ideal to take Hashscan users over to sourcify - but at the same time I think for the people that want to consume the source code its not a bad experience for their needs.
- We plan a phase 3 where we take on the challenge of how to display all the data associated with SC. As a reference there is probably a reason why Etherscan has a tab design - because over time there is a ton of data to display that cannot be easily displayed in a single page view (source code, recent contract calls, traceability etc.). We probably won't do tabs - but maybe break out pages? boxes where a large volume of info can be expanded and collapsed? This needs some thought and design which having a phase 3 will give us some breathing room to do right.

**Comment by SimiHunjan** [comment]
@Nana-EC @dougvk  any concerns with the above suggestion?

**Comment by Nana-EC** [comment]
> @Nana-EC @dougvk  any concerns with the above suggestion?

Nope, I'm in agreement

**Comment by dougvk** [comment]
LGTM :shipit:

**Comment by Reccetech** [comment]
I am unable to verify a Remix generated smart contract on the stage2 staging instance with an error message that the files don't match. The verification works fine on the main Hashscan instance using the beta sourcify wiht a perfect match. 
Contract: https://hashscan-latest.hedera-devops.com/testnet/contract/0.0.5839871
[StorageSC files.zip](https://github.com/hashgraph/hedera-mirror-node-explorer/files/13271731/StorageSC.files.zip)
